name: power_monitor
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.63.0   # For line charts
  provider: ^6.1.0    # For state management (optional)
  http: ^1.2.1        # Latest version for making HTTP requests
  gauge_indicator: ^0.4.3  # Correct placement
  shelf: ^1.3.0       # For backend-related features (if needed)
  cupertino_icons: ^1.0.8  # iOS-style icons
  syncfusion_flutter_gauges: ^28.2.11
  syncfusion_flutter_charts: ^28.2.11
  pdf: ^3.10.4
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
